# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Copyright 2023 MNX Cloud, Inc.

- name: Install cloud-init
  dnf:
    name:
      - cloud-init
      - cloud-utils-growpart
      - dracut-config-generic

- name: Enable cloud-init services
  service:
    name: "{{ item }}"
    enabled: true
  with_items:
    - cloud-config
    - cloud-init
    - cloud-init-local
    - cloud-final

#- name: Configure cloud-init user name
#  replace:
#    dest: /etc/cloud/cloud.cfg
#    regexp: '^(\s+name:).*$'
#    replace: "\\1 {{ cloud_init_user }}"
#  when: cloud_init_user | length > 0
