#!/usr/bin/env bash

#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

# Copyright 2014, Joyent Inc. All rights reserved
# Copyright 2023 MNX Cloud, Inc.

# For scripts that should be run on first boot only

# load common functions and vars
# shellcheck disable=SC1091
. /lib/smartdc/lib_smartdc_scripts.cfg

lib_smartdc_info "Start of $(basename "$0") script"

# Set root password if root_pw is set in the image manifest
(/lib/smartdc/set-rootpassword)

# Set hostid
(/lib/smartdc/set-hostid)

# Disable firstboot once all scripts are run
lib_smartdc_info "Disabling firstboot"
touch /lib/smartdc/.firstboot-complete-do-not-delete

exit 0
