#!/usr/bin/env bash

#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

# Copyright 2014, Joyent Inc. All rights reserved
# Copyright 2023 MNX Cloud, Inc.

# For scripts that should be run on first boot only

# load common functions and vars
# shellcheck disable=SC1091
. /lib/smartdc/lib_smartdc_scripts.cfg

lib_smartdc_info "Start of $(basename "$0") script"

# Set root password if root_pw is set in the image manifest
(/lib/smartdc/set-rootpassword)

# Set hostid
(/lib/smartdc/set-hostid)

#
# Make sure the localhost has a hostname alias in the zone's
# /etc/hosts file
#
lib_smartdc_info "Ensuring /etc/hosts contains $HOSTNAME"
hname=$HOSTNAME
hostfile=/etc/hosts
tmpfile=$(mktemp /dev/shm/hosts.XXXXXX)
if [[ -f $hostfile && ! -h $hostfile ]]; then
	# use awk to search and append to loopback in one command
	awk -v hname="$hname" '{
	    if ($1 ~ /^127\./ && index($0, hname) == 0) {
		printf("%s %s\n", $0, hname);
	    } else {
		print $0
	    }
	}' $hostfile > "$tmpfile"
	mv "$tmpfile" "$hostfile"
	chmod 644 $hostfile
fi

# Disable firstboot once all scripts are run
lib_smartdc_info "Disabling firstboot"
touch /lib/smartdc/.firstboot-complete-do-not-delete

exit 0
