#!/usr/bin/env bash

#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

# Copyright 2014, Joyent Inc. All rights reserved
# Copyright 2023 MNX Cloud, Inc.
#
# This script sets the password for the root user if this:
#
#  "users": [{"name": "root"}]
#
# has been set in the image manifest.
#
# This script must only be run once via firstboot. The script will first check
# /etc/shadow to ensure a root password is not being overwritten.

# load common functions and vars
# shellcheck disable=SC1091
. /lib/smartdc/lib_smartdc_scripts.cfg

lib_smartdc_info "Start of $(basename "$0") script"

# Check /etc/shadow. If root pass is set, exit so we don't clobber a users
# already set password.
passset=$(awk -F':' '/root/ {print $2;}' /etc/shadow )
if [[ -n $passset ]] && [[ $passset != '!!' ]]; then
  lib_smartdc_fatal "The root password already set in /etc/shadow. Extiting."
fi

# Check if root_pw is set in meta data
pass=$(${MDATA_GET_BIN:?} root_pw)
ret="$?"
if (( ret == 0 )) ; then
    lib_smartdc_info "Setting root password to value of meta-data root_pw."
    echo "root:${pass}" | chpasswd
else
    lib_smartdc_info "No root password set in root_pw. Skipping."
fi
