# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Copyright 2023 MNX Cloud, Inc.

---

- name: Running tasks for distribution
  include_tasks: "{{ lookup('first_found', possible_files) }}"
  vars:
    distro: "{{ ansible_distribution }}"
    ver: "{{ ansible_distribution_version }}"
    major: "{{ ansible_distribution_major_version }}"
    family: "{{ ansible_os_family }}"
    possible_files:
      - "{{ distro }}_{{ ver }}.yml"
      - "{{ distro }}_{{ major }}.yml"
      - "{{ distro }}.yml"
      - "{{ family }}.yml"

- name: Running common tasks for any distribution any version - common.yml
  include_tasks: common.yml
