# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Copyright 2023 MNX Cloud, Inc.

---

- name: Remove unwanted packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
    purge: true
  loop:
    - snapd
    - linux-headers-generic
    - linux-headers-*
    - linux-firmware
    - byobu
    - eatmydata
    - fonts-ubuntu-console
    - fwupd
    - fwupd-signed
    - landscape-common
    - laptop-detect
    - plymouth
    - plymouth-theme-ubuntu-text
    - powermgmt-base
    - publicsuffix
    - open-vm-tools

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: yes