# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Copyright 2024 MNX Cloud, Inc.

---

- name: Remove unwanted packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
    purge: true
  loop:
    - amd64-microcode
    - binutils
    - binutils-common
    - binutils-x86-64-linux-gnu
    - byobu
    - eatmydata
    - fonts-ubuntu-console
    - fwupd
    - fwupd-signed
    - iucode-tool
    - landscape-common
    - laptop-detect
    - linux-firmware
    - linux-headers-*
    - linux-headers-generic
    - open-vm-tools
    - plymouth
    - plymouth-theme-ubuntu-text
    - powermgmt-base
    - publicsuffix
    - snapd
    - thermald
    - upower
    - usbmuxd
    - wireless-regdb

- name: Install packages that may have been unavailable during install
  ansible.builtin.apt:
    name "{{ item }}"
  loop:
    - net-tools
    - nftables
    - iptables

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: yes

- name: Remove snap cruft from root's homedir
  file:
    dest: /root/snap
    state: absent

- name: Restore SSH listening behavior
  file:
    dest: "/etc/systemd/{{ item }}"
    state: absent
  loop:
    - /ssh.service.d/00-socket.conf
    - /ssh.socket.d/addresses.conf

# for some reason the 24.04 installer doesn't run this meaning a stale
# ds=nocloud-net persists
- name: Run update-grub2
  shell: update-grub2
  ignore_errors: true
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'noble'
