---

- name: Remove unwanted packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
    purge: true
  loop:
    - snapd
    - linux-headers-generic
    - linux-headers-*
    - linux-firmware
    - byobu
    - eatmydata
    - fonts-ubuntu-console
    - fwupd
    - fwupd-signed
    - landscape-common
    - laptop-detect
    - plymouth
    - plymouth-theme-ubuntu-text
    - powermgmt-base
    - publicsuffix

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: yes