---

- name: Remove unwanted packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  loop:
    - snap
    - linux-headers-generic
    - linux-headers-*
    - linux-firmware
    - byobu
    - eatmydata
    - fonts-ubuntu-console
    - fwupd
    - fwupd-signed
    - landscape-common
    - laptop-detect
    - plymouth
    - plymouth-theme-ubuntu-text
    - powermgmt-base
    - publicsuffix

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: yes

- name: Remove cached deb files
  apt:
    clean: yes

- name: Remove apt sources cache
  ansible.builtin.file:
    path: /var/lib/apt/lists/us.archive.ubuntu.com_ubuntu_dists_*
    state: absent
