# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Copyright 2023 MNX Cloud, Inc.

# An Ansible playbook that configures a SmartOS image
---
- name: SmartOS
  hosts: default
  become: true

  roles:
    #- setup_cloud_init
    - smartos_guest
    - cleanup_vm
